// Code generated by goctl. DO NOT EDIT.
package types

type AddRequest struct {
	Book  string `form:"book"`
	Price int64  `form:"price"`
}

type AddResponse struct {
	Ok bool `json:"ok"`
}

type CheckRequest struct {
	Book string `form:"book"`
}

type CheckResponse struct {
	Found bool  `json:"found"`
	Price int64 `json:"price"`
}
