// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

package adder

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	AddRequest struct {
		Book  string `json:"book,omitempty"`
		Price int64  `json:"price,omitempty"`
	}

	AddResponse struct {
		Ok bool `json:"ok,omitempty"`
	}
)
